name: Deploy to SSH VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the main branch
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Node.js and PM2

      # Connect to remote server via SSH to start the bot using PM2
      - name: Start bot with PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/loick/github/turing-ai.link
            npm run git
            npm i
            npm run build
            nvm use 18
            pm2 reload TuringLink
